#!/usr/bin/env python3
"""Build the release artifacts the installer and auto-updater consume.

Outputs (in --out):
  Quake_Live_Launcher_v5-alpha.zip          install archive, includes release.json
  Quake_Live_Launcher_v5-alpha.zip.sha256   sha256sum-format checksum
  version.json                              manifest the updater checks on launch
  quake-live-launcher-installer.sh          standalone installer (embeds qll_update.py)

CI runs this, and the tests run the exact same code against a local HTTP
server, so what is tested is what ships.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import stat
import subprocess
import time
import zipfile

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE_NAME = "Quake_Live_Launcher_v5-alpha.zip"
INSTALLER_NAME = "quake-live-launcher-installer.sh"
CHANNEL_TAG = "v5-alpha-latest"
TOP_LEVEL_FILES = ("launcher.py", "launcher_gui.py", "qll_update.py", "install.sh", "uninstall.sh", "run.sh", "README.md")
TREES = ("resources", "solo_engine")
PAYLOAD_GLOBS = ("launcher_impl.py.gz.b64part*", "launcher_gui_impl.py.gz.b64part*")
HEREDOC = "QLL_UPDATER_SOURCE_EOF"


def shipped_files(root: Path = ROOT) -> list[Path]:
    """Relative paths of every file in the install archive (except release.json)."""
    files = {Path(name) for name in TOP_LEVEL_FILES}
    for pattern in PAYLOAD_GLOBS:
        files.update(p.relative_to(root) for p in root.glob(pattern))
    for tree in TREES:
        for path in (root / tree).rglob("*"):
            if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc":
                files.add(path.relative_to(root))
    return sorted(files)


def app_version(root: Path = ROOT) -> str:
    match = re.search(r'^APP_VERSION = "([^"]+)"', (root / "launcher.py").read_text(encoding="utf-8"), re.M)
    if not match:
        raise SystemExit("APP_VERSION not found in launcher.py")
    return match.group(1)


def git_commit(root: Path = ROOT) -> str:
    try:
        return subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True, timeout=5).stdout.strip()
    except Exception:
        return ""


def build_archive(out: Path, release: dict, root: Path = ROOT) -> Path:
    archive = out / ARCHIVE_NAME
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for rel in shipped_files(root):
            source = root / rel
            info = zipfile.ZipInfo(rel.as_posix(), date_time=time.localtime(source.stat().st_mtime)[:6])
            mode = source.stat().st_mode
            info.external_attr = ((stat.S_IFREG | (0o755 if mode & 0o111 else 0o644)) & 0xFFFF) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, source.read_bytes())
        info = zipfile.ZipInfo("release.json", date_time=time.localtime()[:6])
        info.external_attr = ((stat.S_IFREG | 0o644) & 0xFFFF) << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        zf.writestr(info, json.dumps(release, indent=2) + "\n")
    return archive


def build_installer(out: Path, root: Path = ROOT) -> Path:
    source = (root / "qll_update.py").read_text(encoding="utf-8")
    if HEREDOC in source:
        raise SystemExit(f"qll_update.py must not contain the heredoc marker {HEREDOC}")
    script = f"""#!/usr/bin/env bash
# Quake Live Launcher installer.
#
# Downloads the latest verified release from GitHub
# ({CHANNEL_TAG} on github.com/BigCatMellow/Quake_Live_Launcher), checks its
# SHA-256, and installs it into your home folder - no sudo needed. After that the
# launcher checks for updates every time it starts, installs them, and restarts.
#
# Usage: bash {INSTALLER_NAME} [--yes]
# Generated by tools/build_release.py from qll_update.py; do not edit by hand.
set -euo pipefail
if [ "$(id -u)" = "0" ] && [ "${{QLL_ALLOW_ROOT:-0}}" != "1" ]; then
  echo "Please run this as your normal user (not with sudo); it installs into your home folder." >&2
  exit 2
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "Python 3 is required. On Mint/Ubuntu: sudo apt install python3" >&2
  exit 1
fi
QLL_TMP="$(mktemp -d)"
trap 'rm -rf "$QLL_TMP"' EXIT
cat > "$QLL_TMP/qll_update.py" <<'{HEREDOC}'
{source.rstrip()}
{HEREDOC}
python3 "$QLL_TMP/qll_update.py" --install "$@"
"""
    path = out / INSTALLER_NAME
    path.write_text(script, encoding="utf-8")
    path.chmod(0o755)
    return path


def build(out: Path, commit: str | None = None, built_at: str | None = None, root: Path = ROOT) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    release = {
        "source": "release",
        "channel": CHANNEL_TAG,
        "app_version": app_version(root),
        "commit": commit or git_commit(root) or "unknown",
        "built_at": built_at or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    archive = build_archive(out, release, root)
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    (out / f"{ARCHIVE_NAME}.sha256").write_text(f"{digest}  {ARCHIVE_NAME}\n", encoding="utf-8")
    manifest = dict(release, archive=ARCHIVE_NAME, sha256=digest, installer=INSTALLER_NAME)
    (out / "version.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    build_installer(out, root)
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default="dist")
    parser.add_argument("--commit")
    args = parser.parse_args()
    manifest = build(Path(args.out), commit=args.commit)
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
